/**
 * Type definitions for Schema Editor state management.
 *
 * These types define the structure of schema fields, validation rules,
 * and state management interfaces for the visual schema editor.
 */

/**
 * Field type enumeration matching JSON Schema types
 */
export type FieldType = 'string' | 'number' | 'boolean' | 'array' | 'object';

/**
 * Field creation source
 * - 'ai': Field was generated by AI and needs review
 * - 'user': Field was manually created by user
 * - 'template': Field was imported from a template
 * - 'existing': Field existed before AI generation (preserved)
 */
export type FieldCreatedBy = 'ai' | 'user' | 'template' | 'existing';

/**
 * Validation rules for schema fields
 *
 * Supports JSON Schema validation properties:
 * - String: pattern, minLength, maxLength, enum
 * - Number: minimum, maximum, multipleOf
 * - Array: minItems, maxItems, uniqueItems
 * - Object: minProperties, maxProperties
 */
export interface ValidationRules {
  // String validation
  pattern?: string;
  minLength?: number;
  maxLength?: number;
  format?: 'date' | 'date-time' | 'time' | 'email' | 'uri' | 'uuid';

  // Number validation
  minimum?: number;
  maximum?: number;
  exclusiveMinimum?: number;
  exclusiveMaximum?: number;
  multipleOf?: number;

  // Array validation
  minItems?: number;
  maxItems?: number;
  uniqueItems?: boolean;

  // Object validation
  minProperties?: number;
  maxProperties?: number;

  // Enum validation (works with any type)
  enum?: Array<string | number | boolean>;

  // Custom validation (extensible)
  [key: string]: unknown;
}

/**
 * Visual metadata for field display
 */
export interface FieldVisualMetadata {
  /** Custom color for field card (hex or CSS color) */
  color?: string;

  /** Icon identifier (e.g., lucide icon name) */
  icon?: string;

  /** Whether nested fields are collapsed */
  collapsed?: boolean;

  /** Custom display properties */
  [key: string]: unknown;
}

/**
 * Schema field structure matching database schema
 *
 * Represents a single field in the extraction schema with all its properties,
 * validation rules, and metadata.
 */
export interface SchemaField {
  /** Unique field identifier (UUID) */
  id: string;

  /** Reference to parent schema (null for draft fields) */
  schema_id?: string | null;

  /** Session identifier for draft/unsaved schemas */
  session_id: string;

  /** Full path for nested fields (e.g., "root.party.name") */
  field_path: string;

  /** Field name (last segment of field_path) */
  field_name: string;

  /** Field data type */
  field_type: FieldType;

  /** Field description for documentation */
  description?: string | null;

  /** Whether field is required in the schema */
  is_required: boolean;

  /** Reference to parent field for nested structures */
  parent_field_id?: string | null;

  /** Position in the field list (0-indexed) */
  position: number;

  /** JSON Schema validation rules */
  validation_rules: ValidationRules;

  /** Visual display metadata */
  visual_metadata: FieldVisualMetadata;

  /** Field creation source */
  created_by: FieldCreatedBy;

  /** Creation timestamp (ISO 8601) */
  created_at?: string;

  /** Last update timestamp (ISO 8601) */
  updated_at?: string;
}

/**
 * Optimistic update operation
 *
 * Tracks pending operations for rollback on failure.
 */
export interface OptimisticUpdate {
  /** Unique operation identifier */
  id: string;

  /** Type of operation */
  type: 'add' | 'update' | 'delete' | 'reorder';

  /** Field ID affected by operation */
  fieldId: string;

  /** Previous state for rollback */
  previousState?: SchemaField | SchemaField[];

  /** New state (for update/add operations) */
  newState?: SchemaField | SchemaField[];

  /** Operation timestamp */
  timestamp: number;
}

/**
 * Validation error structure
 */
export interface ValidationError {
  /** Field ID with error */
  fieldId: string;

  /** Field path for display */
  fieldPath: string;

  /** Error message */
  message: string;

  /** Error severity */
  severity: 'error' | 'warning';

  /** Error source */
  source: 'zod' | 'backend' | 'realtime';
}

/**
 * Backend validation response
 */
export interface BackendValidationResponse {
  /** Whether schema is valid */
  valid: boolean;

  /** Validation errors */
  errors: string[];

  /** Validation warnings */
  warnings: string[];

  /** Compiled schema (if valid) */
  compiled_schema?: Record<string, unknown> | null;
}

/**
 * Schema metadata
 */
export interface SchemaMetadata {
  /** Schema name */
  name?: string;

  /** Schema description */
  description?: string;

  /** Total field count */
  field_count: number;

  /** Last saved timestamp */
  last_saved?: string;

  /** Schema version number */
  version?: number;
}

/**
 * Conflict resolution strategy
 */
export type ConflictResolution = 'local' | 'remote' | 'merge';

/**
 * Real-time sync event
 */
export interface SyncEvent {
  /** Event type */
  eventType: 'INSERT' | 'UPDATE' | 'DELETE';

  /** Affected field */
  field: SchemaField;

  /** Event timestamp */
  timestamp: string;

  /** Whether event originated from this client */
  isLocal: boolean;
}
