#!/bin/sh
set -e

echo "======================================"
echo "Legal AI Frontend - Runtime Configuration"
echo "======================================"

# Default values (production defaults as fallback)
DEFAULT_API_BASE_URL="https://legal-ai-api.augustyniak.ai"
DEFAULT_SUPABASE_URL="https://uwillfqffptnwrzgoejs.supabase.co"
DEFAULT_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3aWxsZnFmZnB0bndyemdvZWpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMzM4MjAsImV4cCI6MjA1NjkwOTgyMH0.UY9ovgZ9kEroeKuOa9YmNb80pX-uaqXPzqjyC-TgVt0"

# Process runtime environment variables with fallbacks
API_BASE_URL="${NEXT_PUBLIC_API_BASE_URL:-$DEFAULT_API_BASE_URL}"
SUPABASE_URL="${NEXT_PUBLIC_SUPABASE_URL:-$DEFAULT_SUPABASE_URL}"
SUPABASE_ANON_KEY="${NEXT_PUBLIC_SUPABASE_ANON_KEY:-$DEFAULT_SUPABASE_ANON_KEY}"

# Log configuration (mask sensitive data)
echo "Configuration Status:"
echo "  NEXT_PUBLIC_API_BASE_URL: ${API_BASE_URL}"
echo "  NEXT_PUBLIC_SUPABASE_URL: ${SUPABASE_URL}"
echo "  NEXT_PUBLIC_SUPABASE_ANON_KEY: $([ ! -z "$SUPABASE_ANON_KEY" ] && echo '***configured***' || echo 'NOT SET')"
echo "  BACKEND_API_KEY: $([ ! -z "$BACKEND_API_KEY" ] && echo '***configured***' || echo 'NOT SET')"

# Generate runtime config file that will be loaded by the browser
echo "Generating runtime configuration file..."
mkdir -p ./public

cat > ./public/env-config.js << EOF
/**
 * Runtime Environment Configuration
 * Generated by docker-entrypoint.sh at container startup
 * Loaded via <Script> tag in app/layout.tsx
 */
window.__env = {
  NEXT_PUBLIC_API_BASE_URL: "${API_BASE_URL}",
  NEXT_PUBLIC_SUPABASE_URL: "${SUPABASE_URL}",
  NEXT_PUBLIC_SUPABASE_ANON_KEY: "${SUPABASE_ANON_KEY}"
};

// Log that runtime config was loaded successfully
console.log('[Runtime Config] Environment variables loaded from docker-entrypoint.sh');
EOF

echo "Runtime configuration file created successfully ✓"
echo "======================================"

# Set server-side environment variables (for API routes)
export BACKEND_API_KEY="${BACKEND_API_KEY:-dummy-key}"

# Start the Next.js server
echo "Starting Next.js server..."
exec "$@"