#!/bin/sh
set -e

echo "======================================"
echo "Legal AI Frontend - Runtime Configuration"
echo "======================================"

# Default values (production defaults as fallback)
DEFAULT_API_BASE_URL="https://legal-ai-api.augustyniak.ai"
DEFAULT_SUPABASE_URL="https://uwillfqffptnwrzgoejs.supabase.co"
DEFAULT_SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3aWxsZnFmZnB0bndyemdvZWpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMzM4MjAsImV4cCI6MjA1NjkwOTgyMH0.UY9ovgZ9kEroeKuOa9YmNb80pX-uaqXPzqjyC-TgVt0"

# Process runtime environment variables with fallbacks
API_BASE_URL="${NEXT_PUBLIC_API_BASE_URL:-$DEFAULT_API_BASE_URL}"
SUPABASE_URL="${NEXT_PUBLIC_SUPABASE_URL:-$DEFAULT_SUPABASE_URL}"
SUPABASE_ANON_KEY="${NEXT_PUBLIC_SUPABASE_ANON_KEY:-$DEFAULT_SUPABASE_ANON_KEY}"

# Log configuration (mask sensitive data)
echo "Configuration Status:"
echo "  NEXT_PUBLIC_API_BASE_URL: ${API_BASE_URL}"
echo "  NEXT_PUBLIC_SUPABASE_URL: ${SUPABASE_URL}"
echo "  NEXT_PUBLIC_SUPABASE_ANON_KEY: $([ ! -z "$SUPABASE_ANON_KEY" ] && echo '***configured***' || echo 'NOT SET')"
echo "  BACKEND_API_KEY: $([ ! -z "$BACKEND_API_KEY" ] && echo '***configured***' || echo 'NOT SET')"

# Generate runtime config file that will be loaded by the browser
echo "Generating runtime configuration file..."
mkdir -p ./public

cat > ./public/env-config.js << EOF
/**
 * Runtime Environment Configuration
 * Generated by docker-entrypoint.sh at container startup
 * Loaded via <Script> tag in app/layout.tsx
 */
window.__env = {
  NEXT_PUBLIC_API_BASE_URL: "${API_BASE_URL}",
  NEXT_PUBLIC_SUPABASE_URL: "${SUPABASE_URL}",
  NEXT_PUBLIC_SUPABASE_ANON_KEY: "${SUPABASE_ANON_KEY}"
};

// Log that runtime config was loaded successfully
console.log('[Runtime Config] Environment variables loaded from docker-entrypoint.sh');
EOF

echo "Runtime configuration file created successfully ✓"

# ==========================================================================
# Runtime Environment Injection into Built JS
# ==========================================================================
# Next.js inlines NEXT_PUBLIC_* at build time. In standalone Docker builds,
# process.env.NEXT_PUBLIC_* references become literal strings in the bundle.
# We patch these build-time placeholders with actual runtime values.
echo "Injecting runtime environment into built JS files..."

# Build-time placeholder for API_BASE_URL (the value baked into the image)
# The image was built with this value; we replace it with the runtime value.
BUILD_TIME_API_URL="${BUILD_TIME_API_BASE_URL:-}"

if [ -n "$API_BASE_URL" ]; then
  # Patch built Next.js files to replace empty build-time env values
  # with actual runtime values. Uses a separate Node.js script to avoid
  # shell escaping issues with complex patterns.
  node patch-env.js
  echo "  API_BASE_URL injected: ${API_BASE_URL} ✓"
fi

echo "======================================"

# Set server-side environment variables (for API routes)
export BACKEND_API_KEY="${BACKEND_API_KEY:-dummy-key}"

# Start the Next.js server
echo "Starting Next.js server..."
exec "$@"