#!/usr/bin/env node
// design-sync build step (cfg.buildCmd). The frontend is a Next.js app, not a
// published package, so this script materialises a tiny package at
// frontend/.ds-pkg/ (gitignored) that the converter can treat as a built DS:
//
//   frontend/.ds-pkg/
//     package.json          name/version/main/types
//     src/index.ts          re-exports of components/editorial + components/ui
//     dist/index.js         bundle entry (re-exports src, esbuild follows .ts)
//     dist/types/**/*.d.ts  tsc --emitDeclarationOnly over src/index.ts
//     dist/styles.css       Tailwind 4 compile of .design-sync/tailwind.css
//
// Run from the repo root: `node .design-sync/build.mjs`.
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const FRONTEND = join(ROOT, "frontend");
const PKG = join(FRONTEND, ".ds-pkg");
const DS_SYNC = join(ROOT, ".ds-sync"); // staged converter scripts + their node_modules (tailwind cli, typescript)

const frontendPkg = JSON.parse(readFileSync(join(FRONTEND, "package.json"), "utf8"));

// The converter deps live in the gitignored .ds-sync/ (staged per machine by the
// design-sync skill). Fail early with the install command rather than an ENOENT
// deep inside tsc / tailwind.
const tsc = join(DS_SYNC, "node_modules/typescript/bin/tsc");
const twCli = join(DS_SYNC, "node_modules/@tailwindcss/cli/dist/index.mjs");
for (const [bin, pkg] of [[tsc, "typescript"], [twCli, "@tailwindcss/cli"]]) {
  if (!existsSync(bin)) {
    console.error(`\u2717 ${bin} missing \u2014 run: (cd .ds-sync && npm i esbuild ts-morph @types/react typescript @tailwindcss/cli playwright)`);
    process.exit(1);
  }
}

// -- 1. entry: components/editorial + components/ui/*.tsx + ui/skeletons/ ---
// ui/skeletons/ ships via its barrel (#657). Star re-exports drop ambiguous
// names silently, so a new ui/* export must not reuse SkeletonCard or
// SkeletonText (the barrel) or Skeleton (ui/skeleton.tsx) — see NOTES.md.
// logo.tsx is left out: it renders a brand asset by app-relative URL through
// next/image, which has nothing to show outside the app.
const uiFiles = readdirSync(join(FRONTEND, "components/ui"))
  .filter((f) => f.endsWith(".tsx") && f !== "logo.tsx")
  .sort();
const entryLines = [
  "// generated by .design-sync/build.mjs - do not edit",
  'export * from "../../components/editorial";',
  ...uiFiles.map((f) => `export * from "../../components/ui/${f.replace(/\.tsx$/, "")}";`),
  'export * from "../../components/ui/skeletons";',
];

rmSync(PKG, { recursive: true, force: true });
mkdirSync(join(PKG, "src"), { recursive: true });
mkdirSync(join(PKG, "dist"), { recursive: true });
writeFileSync(join(PKG, "src/index.ts"), entryLines.join("\n") + "\n");
writeFileSync(join(PKG, "dist/index.js"), 'export * from "../src/index.ts";\n');
writeFileSync(
  join(PKG, "package.json"),
  JSON.stringify(
    {
      name: "@juddges/design-system",
      version: frontendPkg.version,
      private: true,
      main: "dist/index.js",
      module: "dist/index.js",
      types: "dist/types/.ds-pkg/src/index.d.ts",
      peerDependencies: { react: frontendPkg.dependencies.react, "react-dom": frontendPkg.dependencies["react-dom"] },
    },
    null,
    2,
  ) + "\n",
);

// -- 2. .d.ts tree via tsc ---------------------------------------------------
// rootDir is frontend/ so the emitted tree mirrors the source layout and
// relative imports between components stay valid.
writeFileSync(
  join(PKG, "tsconfig.json"),
  JSON.stringify(
    {
      extends: "../tsconfig.json",
      compilerOptions: {
        noEmit: false,
        declaration: true,
        emitDeclarationOnly: true,
        incremental: false,
        outDir: "dist/types",
        rootDir: "..",
        plugins: [],
        // Real next/* types here; the next/link + next/image shims apply only to
        // the esbuild bundle (.design-sync/tsconfig.json) - tsc's rootDir forbids them.
        paths: { "@/*": ["../*"] },
      },
      include: ["src/index.ts"],
    },
    null,
    2,
  ) + "\n",
);
try {
  execFileSync(process.execPath, [tsc, "-p", join(PKG, "tsconfig.json")], { stdio: "inherit" });
} catch (e) {
  // tsc exits non-zero on type errors but still emits; only a missing tree is fatal.
  if (e.code === "ENOENT") throw e;
  console.error("  ! tsc reported errors (declarations still emitted if possible)");
}
const typesEntry = join(PKG, "dist/types/.ds-pkg/src/index.d.ts");
if (!existsSync(typesEntry)) {
  console.error(`✗ ${typesEntry} not emitted`);
  process.exit(1);
}

// -- 3. compiled Tailwind stylesheet -----------------------------------------
// cwd = frontend/ so Tailwind's automatic source detection and the
// `@import "tailwindcss"` / `@plugin` resolution inside globals.css behave as
// in the app build.
execFileSync(
  process.execPath,
  [twCli, "-i", join(ROOT, ".design-sync/tailwind.css"), "-o", join(PKG, "dist/styles.css"), "--minify"],
  { cwd: FRONTEND, stdio: "inherit" },
);

const dtsCount = (() => {
  let n = 0;
  const walk = (d) => {
    for (const f of readdirSync(d, { withFileTypes: true })) {
      if (f.isDirectory()) walk(join(d, f.name));
      else if (f.name.endsWith(".d.ts")) n++;
    }
  };
  walk(join(PKG, "dist/types"));
  return n;
})();
console.error(`✓ .ds-pkg: ${uiFiles.length + 3} entry modules, ${dtsCount} .d.ts, styles.css ${readFileSync(join(PKG, "dist/styles.css")).length} bytes`);
