"use client";

import * as React from "react";
import { useState, useEffect, useCallback, useMemo } from "react";
import {
  ResizablePanelGroup,
  ResizablePanel,
  ResizableHandle,
} from "@/components/ui/resizable";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { ChatPane } from "./ChatPane";
import { CanvasPane } from "./CanvasPane";
import { VersionsTab } from "./versions/VersionsTab";
import { useSchemaEditorStore } from "@/hooks/schema-editor/useSchemaEditorStore";
import { schemaService } from "@/lib/schema-editor/service";
import { toast } from "sonner";
import { Layers, History } from "lucide-react";
import type { SchemaField } from "@/hooks/schema-editor/types";

/**
 * Props for the SchemaStudioLayout component
 */
interface SchemaStudioLayoutProps {
  /** Session identifier for tracking draft schemas */
  sessionId: string;
  /** Optional collection ID to scope the schema */
  collectionId?: string;
  /** Optional initial collection name for display */
  collectionName?: string;
  /** Callback to open preview dialog */
  onPreviewClick?: () => void;
}

/**
 * SchemaStudioLayout - Main split-pane container for the visual schema editor
 *
 * This component implements the core layout with:
 * - Left pane (60%): Visual canvas for manual field editing
 * - Right pane (40%): Chat interface for AI-driven schema generation
 * - Resizable divider with localStorage persistence
 *
 * @example
 * ```tsx
 * <SchemaStudioLayout
 *   sessionId="session-123"
 *   collectionId="collection-456"
 *   collectionName="Tax Documents"
 * />
 * ```
 */
export function SchemaStudioLayout({
  sessionId,
  collectionId,
  collectionName,
  onPreviewClick,
}: SchemaStudioLayoutProps) {
  // Storage key for persisting pane sizes
  const STORAGE_KEY = "schema-studio-layout-sizes";

  // Default layout: 60% canvas (left), 40% chat (right)
  const DEFAULT_SIZES = [60, 40];

  // State for panel sizes with localStorage persistence
  const [panelSizes, setPanelSizes] = useState<number[]>(DEFAULT_SIZES);

  // Get store state and actions
  const { fields, metadata, setFields, markDirty, addField } = useSchemaEditorStore();

  // Convert current fields to format expected by ChatPane (JSON Schema properties)
  const currentSchemaFields = useMemo(() => {
    if (fields.length === 0) return undefined;

    const properties: Record<string, unknown> = {};
    fields
      .filter((f) => !f.parent_field_id) // Only root-level fields
      .forEach((field) => {
        properties[field.field_name] = {
          type: field.field_type,
          description: field.description || "",
        };
      });

    return properties;
  }, [fields]);

  // Get set of existing field names for deduplication
  const existingFieldNames = useMemo(() => {
    return new Set(fields.map((f) => f.field_name));
  }, [fields]);

  /**
   * Handle schema generated by AI
   *
   * Parses the JSON Schema response and merges new fields into the store.
   * New fields are marked with created_by: 'ai' for visual distinction.
   */
  const handleSchemaGenerated = useCallback(
    (schema: Record<string, unknown>, generatedPrompt: string) => {
      // Parse JSON Schema into SchemaField array
      const parsedFields = schemaService.parseJsonSchemaToFields(
        schema as any,
        null,
        'root',
        existingFieldNames
      );

      // Filter to only new fields (not already in store)
      const newFields = parsedFields.filter(
        (parsedField) => !existingFieldNames.has(parsedField.field_name)
      );

      if (newFields.length === 0) {
        toast.info("No new fields to add", {
          description: "The AI suggestions overlap with existing fields.",
        });
        return;
      }

      // Add each new field to the store
      // Position them after existing fields
      const startPosition = fields.length;
      newFields.forEach((newField, index) => {
        addField({
          session_id: sessionId,
          field_path: newField.field_path,
          field_name: newField.field_name,
          field_type: newField.field_type,
          description: newField.description,
          is_required: newField.is_required,
          parent_field_id: newField.parent_field_id,
          validation_rules: newField.validation_rules || {},
          visual_metadata: { needsReview: true },
          created_by: 'ai',
        });
      });

      // Show success toast
      toast.success(`Added ${newFields.length} AI-generated field(s)`, {
        description: `Fields: ${newFields.map((f) => f.field_name).join(", ")}`,
      });
    },
    [fields, existingFieldNames, sessionId, addField]
  );

  // Load saved sizes on mount
  useEffect(() => {
    if (typeof window === "undefined") return;

    const saved = localStorage.getItem(STORAGE_KEY);
    if (saved) {
      try {
        const sizes = JSON.parse(saved);
        if (Array.isArray(sizes) && sizes.length === 2) {
          // Clamp chat pane size to max 40%
          const chatSize = Math.min(sizes[1], 40);
          const canvasSize = 100 - chatSize;
          setPanelSizes([canvasSize, chatSize]);
        }
      } catch (error) {
        console.error("Failed to parse saved layout sizes: ", error);
      }
    }
  }, []);

  // Save sizes when they change
  const handleLayoutChange = (sizes: number[]) => {
    // Ensure chat pane never exceeds 40%
    const chatSize = Math.min(sizes[1], 40);
    const canvasSize = 100 - chatSize;
    const clampedSizes = [canvasSize, chatSize];
    setPanelSizes(clampedSizes);
    if (typeof window !== "undefined") {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(clampedSizes));
    }
  };

  // Get schemaId from store
  const { schemaId } = useSchemaEditorStore();

  // Active tab state
  const [activeTab, setActiveTab] = useState<'fields' | 'versions'>('fields');

  return (
    <div className="h-full w-full overflow-hidden" style={{ height: '100%' }}>
      <ResizablePanelGroup
        direction="horizontal"
        onLayout={handleLayoutChange}
        className="h-full w-full"
        style={{ height: '100%' }}
      >
        {/* Left pane: Visual canvas with tabs */}
        <ResizablePanel
          defaultSize={panelSizes[0]}
          minSize={20}
          maxSize={90}
          className="h-full"
          style={{
            isolation: 'isolate',
            contain: 'layout style paint',
            position: 'relative',
            maxWidth: '100%',
            height: '100%',
          }}
        >
          <div className="h-full w-full overflow-hidden relative flex flex-col" style={{ maxWidth: '100%', width: '100%', height: '100%' }}>
            <Tabs
              value={activeTab}
              onValueChange={(value) => setActiveTab(value as 'fields' | 'versions')}
              className="h-full flex flex-col"
            >
              {/* Tab Navigation */}
              <div className="flex-shrink-0 px-4 pt-3 pb-2 border-b border-border/40 bg-background/50 backdrop-blur-sm">
                <TabsList className="w-auto">
                  <TabsTrigger value="fields" className="gap-1.5">
                    <Layers className="h-4 w-4" />
                    <span>Fields</span>
                  </TabsTrigger>
                  <TabsTrigger value="versions" className="gap-1.5">
                    <History className="h-4 w-4" />
                    <span>Versions</span>
                  </TabsTrigger>
                </TabsList>
              </div>

              {/* Tab Content */}
              <TabsContent value="fields" className="flex-1 overflow-hidden m-0">
                <CanvasPane
                  sessionId={sessionId}
                  collectionId={collectionId}
                  onPreviewClick={onPreviewClick}
                />
              </TabsContent>

              <TabsContent value="versions" className="flex-1 overflow-hidden m-0">
                <VersionsTab
                  schemaId={schemaId}
                />
              </TabsContent>
            </Tabs>
          </div>
        </ResizablePanel>

        {/* Resizable divider */}
        <ResizableHandle withHandle />

        {/* Right pane: Chat interface */}
        <ResizablePanel
          defaultSize={panelSizes[1]}
          minSize={15}
          maxSize={40}
          className="h-full"
          style={{
            isolation: 'isolate',
            contain: 'layout style paint',
            position: 'relative',
            maxWidth: '100%',
            height: '100%',
          }}
        >
          <div className="h-full w-full overflow-hidden relative" style={{ maxWidth: '100%', width: '100%', height: '100%' }}>
            <ChatPane
              sessionId={sessionId}
              collectionId={collectionId}
              collectionName={collectionName}
              schemaName={metadata.name}
              schemaDescription={metadata.description}
              currentSchemaFields={currentSchemaFields}
              onSchemaGenerated={handleSchemaGenerated}
            />
          </div>
        </ResizablePanel>
      </ResizablePanelGroup>
    </div>
  );
}

/**
 * TODO: Implementation checklist
 *
 * [x] Create base layout structure with ResizablePanelGroup
 * [x] Implement localStorage persistence for panel sizes
 * [x] Add ChatPane and CanvasPane components
 * [ ] Add keyboard shortcuts for layout control (Ctrl+[ to focus chat, Ctrl+] to focus canvas)
 * [ ] Add reset layout button (restore to 40/60 default)
 * [ ] Handle mobile responsive behavior (collapse to tabs instead of split)
 * [ ] Add layout state to zustand store for cross-component access
 * [ ] Implement panel collapse/expand animations
 */
