"use client";

import { AlertTriangle, ExternalLink } from "lucide-react";
import Link from "next/link";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { cn } from "@/lib/utils";

interface AIDisclaimerProps {
 className?: string;
 variant?: "banner"|"inline"|"compact";
}

export function AIDisclaimer({ className, variant = "inline" }: AIDisclaimerProps) {
  if (variant === "banner") {
    return (
      <Alert
        className={cn(
          "border-b border-rule bg-parchment text-ink",
          "sticky top-0 z-50 rounded-none border-x-0 border-t-0",
          className
        )}
      >
        <AlertTriangle className="h-4 w-4 text-gold" />
        <AlertDescription className="flex items-center justify-between gap-4">
          <span className="text-sm font-medium font-mono text-ink">
            AI-Generated Content &mdash; Requires Professional Verification
          </span>
          <Link
            href="/legal/disclaimer"
            className="flex items-center gap-1 text-xs font-mono text-ink-soft hover:text-ink transition-colors whitespace-nowrap"
          >
            Full Disclaimer
            <ExternalLink className="h-3 w-3" />
          </Link>
        </AlertDescription>
      </Alert>
    );
  }

  if (variant === "compact") {
    return (
      <div className={cn("flex items-center gap-2 text-xs text-ink-soft font-mono", className)}>
        <AlertTriangle className="h-3 w-3 text-gold" />
        <span>AI-generated content. Verify before use.</span>
        <Link
          href="/legal/disclaimer"
          className="text-ink hover:underline underline-offset-2 font-medium"
        >
          See disclaimer
        </Link>
      </div>
    );
  }

  // Default inline variant
  return (
    <Alert className={cn("border border-rule border-l-2 border-l-gold bg-parchment text-ink rounded-none", className)}>
      <AlertTriangle className="h-4 w-4 text-gold" />
      <AlertDescription className="text-sm">
        <span className="font-semibold text-ink font-mono text-xs uppercase tracking-wide">
          AI-Generated Content &mdash; Requires Professional Verification
        </span>
        <p className="mt-1 text-ink-soft text-xs leading-relaxed">
          This content was generated by AI and should be verified by a qualified professional
          before being relied upon for legal or tax decisions.{" "}
          <Link
            href="/legal/disclaimer"
            className="font-medium text-ink underline underline-offset-2 hover:text-ink-deep"
          >
            Read full disclaimer
          </Link>
        </p>
      </AlertDescription>
    </Alert>
  );
}
