"use client";

import { AlertTriangle, ExternalLink } from "lucide-react";
import Link from "next/link";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { cn } from "@/lib/utils";

interface AIDisclaimerProps {
  className?: string;
  variant?: "banner" | "inline" | "compact";
}

export function AIDisclaimer({ className, variant = "inline" }: AIDisclaimerProps) {
  if (variant === "banner") {
    return (
      <Alert
        className={cn(
          "border-amber-500/50 bg-amber-500/10 dark:bg-amber-500/5",
          "sticky top-0 z-50 rounded-none border-x-0 border-t-0",
          className
        )}
      >
        <AlertTriangle className="h-4 w-4 text-amber-600 dark:text-amber-500" />
        <AlertDescription className="flex items-center justify-between gap-4">
          <span className="text-sm font-medium text-amber-900 dark:text-amber-200">
            AI-Generated Content - Requires Professional Verification
          </span>
          <Link
            href="/legal/disclaimer"
            className="flex items-center gap-1 text-xs font-semibold text-amber-700 hover:text-amber-800 dark:text-amber-400 dark:hover:text-amber-300 transition-colors whitespace-nowrap"
          >
            Full Disclaimer
            <ExternalLink className="h-3 w-3" />
          </Link>
        </AlertDescription>
      </Alert>
    );
  }

  if (variant === "compact") {
    return (
      <div className={cn("flex items-center gap-2 text-xs text-muted-foreground", className)}>
        <AlertTriangle className="h-3 w-3 text-amber-600 dark:text-amber-500" />
        <span>AI-generated content. Verify before use.</span>
        <Link
          href="/legal/disclaimer"
          className="text-primary hover:text-primary/80 font-medium transition-colors duration-200 hover:underline underline-offset-2"
        >
          See disclaimer
        </Link>
      </div>
    );
  }

  // Default inline variant
  return (
    <Alert className={cn("border-amber-500/50 bg-amber-500/10 dark:bg-amber-500/5", className)}>
      <AlertTriangle className="h-4 w-4 text-amber-600 dark:text-amber-500" />
      <AlertDescription className="text-sm">
        <span className="font-semibold text-amber-900 dark:text-amber-200">
          AI-Generated Content - Requires Professional Verification
        </span>
        <p className="mt-1 text-amber-800 dark:text-amber-300">
          This content was generated by AI and should be verified by a qualified professional
          before being relied upon for legal or tax decisions.{" "}
          <Link
            href="/legal/disclaimer"
            className="font-semibold underline underline-offset-2 hover:text-amber-900 dark:hover:text-amber-200"
          >
            Read full disclaimer
          </Link>
        </p>
      </AlertDescription>
    </Alert>
  );
}
